### ISSUE TITLE
systemctl reload glauth-ui stops service

### ISSUE THREAD

**Issue by Jonny007-MKD** [bodsch/ansible-glauth-ui#2]
When I run

    systemctl reload glauth-ui`

the service stopped afterwards.

https://github.com/bodsch/ansible-glauth-ui/blob/97cc6a6f061c706c3775e81f258bc036849c8ee2/templates/init/systemd/glauth-ui.service.j2#L15

I don't know much about golang, but I cannot find any SIGHUP in glauth-ui-light, so probably this is some copy-paste error from a different service?

**Comment by bodsch** [comment]
note for me https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecReload=

**Comment by bodsch** [comment]
A common use case for kill is to send the HUP signal, which tells the processes to reload its settings.

I think that glauth-ui has implemented incorrect signal handling here.
I'll see if I can open a bug report on this.

**Comment by bodsch** [comment]
fixed with 21fb21059326cbca3c735eca782342b43611c1a4
